apiVersion: v1
kind: Service
metadata:
  name: helloworld-server
  namespace: teamdev3
  labels:
    app: helloworld-server
spec:
  selector:
    app: helloworld-server
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-server
  namespace: teamdev3
  labels:
    app: helloworld-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld-server
  template:
    metadata:
      labels:
        app: helloworld-server
    spec:
      containers:
      - name: helloworld-server
        image: camel.uangel.com:5000/helloworld_server:latest
        ports:
        - containerPort: 50051