apiVersion: batch/v1
kind: Job
metadata:
  name: routeguide-client
  namespace: teamdev3
  labels:
    app: routeguide-client
spec:
  template:
    spec:
      containers:
      - name: routeguide-client
        image: camel.uangel.com:5000/route_guide_client:latest
        command: ["./client"]
        args: ["--addr=routeguide-server:50051"]
      restartPolicy: Never
  backoffLimit: 4
  ttlSecondsAfterFinished: 10
